### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [magicalbob/dynamics365#1]
Hi,<br><br>url : https://github.com/magicalbob/dynamics365/blob/01e2fa427abd3a7d989a98fd0204257599e78069/terraform-allinone-azure/provider.tf <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by magicalbob** [comment]
Thanks for spotting my sloppiness @shaybenb . I've replaced those secrets with meaningless text. As it happens those secrets have lapsed anyway, so they were just meaningless text anyway.

**Comment by shaybenb** [comment]
Our Bug Help you to be more Secure and protect your data ?
Buy me a coffee (or more likely a beer)
https://www.paypal.com/paypalme/bugbounty1/150USD
https://www.buymeacoffee.com/bugbounty
☕☕☕☕☕
